#!/usr/bin/env sh

target=iobroker.d.ts

wget -O "$target" https://raw.githubusercontent.com/ioBroker/ioBroker.javascript/master/src/lib/javascript.d.ts

printf '%bPlease comment or remove the "console" declaration in %s!%b\n' \
      '\e[1;31m' \
       "$target" \
       '\e[0m'
