#!/usr/bin/env bash

set -euo pipefail

locations=(home ogd)

script_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

for location in "${locations[@]}"; do
  mapfile -t typescripts < <(find "$script_dir/$location" \
                                  -type f,l \
                                  -name '*.ts' \
                                  -not -iwholename '*/global/*')
  mapfile -t globals < <(find -L \
                              "$script_dir/$location/global" \
                              -type f \
                              -name '*.ts')

  for ts in "${typescripts[@]}"; do
    printf '%s\n' "$ts"

    ts_dir=$(dirname "$ts")

    root_relative="$(realpath --relative-to="$ts_dir" "$script_dir")"

    globals_relative=()
    for global in "${globals[@]}"; do
      globals_relative+=("$(realpath --no-symlinks --relative-to="$ts_dir" "$global")")
    done

    globals_relative_json="$(printf '%s\n' "${globals_relative[@]}" |
                             jq --raw-input . |
                             jq --slurp .)"

    jq --null-input \
       --arg root_relative "$root_relative" \
       --argjson globals "$globals_relative_json" \
       --arg ts "${ts##*/}" \
       '{
          extends: "\($root_relative)/tsconfig.json",
          files: (["\($root_relative)/iobroker.d.ts"] + ($globals | sort) + [$ts]),
          compilerOptions: {
            composite: true,
            rootDir: $root_relative
          }
        }' > "${ts%.ts}.tsconfig.json"

    npx prettier --write "${ts%.ts}.tsconfig.json"

  done
done

mapfile -t tsconfigs < <(find "${locations[@]}" \
                              -mindepth 1 \
                              -type f \
                              -name '*.tsconfig.json' |
                         sort)

paths="$(printf '%s\n' "${tsconfigs[@]}" |
         jq --raw-input '{ path: . }' |
         jq --slurp .)"

jq --null-input \
   --argjson references "$paths" \
  '{
     extends: "./tsconfig.base.json",
     exclude: ["*"],
     references: ($references | sort_by(.path))
  }' > tsconfig.json

npx prettier --write tsconfig.json
