#!/usr/bin/env sh

set -e

script_dir="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"

if scutil --dns | grep --quiet --fixed-strings 'search domain[0] : home.therightstuff.de'; then
  host="${MOUNT:-nest}"
else
  host="${MOUNT:-finn}"
fi

remote_dir=/data/iobroker/scripts
local_dir="$script_dir/host"

mkdir --parents "$local_dir"

if [ $# = 0 ]; then
  sshfs \
    -o noappledouble \
    -o noapplexattr \
    -o transform_symlinks \
    -o no_contain_symlinks \
    -o reconnect \
    -o Compression=no,ServerAliveInterval=15,ServerAliveCountMax=3 \
   "$host:$remote_dir" "$local_dir"
else
  if ! umount "$local_dir"; then
    hash diskutil 2> /dev/null && sudo diskutil unmount force "$local_dir"
  fi
fi
