#!/usr/bin/env sh

set -e

script_dir="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"

if ! scutil --dns | grep --quiet --fixed-strings home.therightstuff.de; then
  host="${MOUNT:-pi}"
else
  host="${MOUNT:-finn}"
fi

remote_dir=/data/iobroker/scripts
local_dir="$script_dir/host"

mkdir --parents "$local_dir"

if [ $# = 0 ]; then
  sshfs "$host:$remote_dir" "$local_dir" -o transform_symlinks
else
  umount "$local_dir"
fi
